# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2016-12-03 12:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredient', models.CharField(max_length=50)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='articles.Article')),
            ],
            options={
                'verbose_name': 'Ingredient',
                'verbose_name_plural': 'Ingrdients',
            },
        ),
        migrations.AlterUniqueTogether(
            name='ingredient',
            unique_together=set([('ingredient', 'article')]),
        ),
        migrations.AlterIndexTogether(
            name='ingredient',
            index_together=set([('ingredient', 'article')]),
        ),
    ]
